[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font]
size = 7

[font.normal]
#family = "ComicMono Nerd Font"
family = "ComicCode"
style = "Medium"

[font.bold]
family = "ComicCode"
style = "Bold"

[font.italic]
family = "ComicCode"
style = "Italic"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 0
y = 0
