[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font]
size = 12.0

[font.normal]
family = "ComicMono Nerd Font"
style = "Normal"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 0
y = 0
