[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font]
size = 11

[font.normal]
# family = "ComicMono Nerd Font"
family = "Comic Code Ligatures"
style = "Medium"

[font.bold]
family = "Comic Code Ligatures"
style = "Bold"

[font.italic]
family = "Comic Code Ligatures"
style = "Italic"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 0
y = 0
